### ISSUE TITLE
status updating is not needed if I run Cud w/o opened files

### ISSUE THREAD

**Issue by Alexey-T** [TodNaz/cuda_discord_status#14]
если я пускаю Куд без файлов -например набить некий файл, то Куд уже сразу по on_start активирует плаг. может убрать активацию по on_start? 

Startup: 340ms, plugins: 200ms (discord_status 187ms, macros 15ms, runner 2ms)

**Comment by Alexey-T** [comment]
190 ms запуск- надо сэкономить это

**Comment by TodNaz** [comment]
Тогда можно вынести автоподключение в настройки, и поставить по умолчанию чтобы автоподключение не происходило.

**Comment by Alexey-T** [comment]
Можно и так
