### ISSUE TITLE
I suggest to name the plugin to 'Discord Status', folder cuda_discord_status

### ISSUE THREAD

**Issue by Alexey-T** [TodNaz/cuda_discord_status#3]
And ini file: cuda_discord_status.ini .

**Comment by Alexey-T** [comment]
Файл install.inf тогда станет
```

[info]
title=Discord Status
desc=Plugin for displaying your status in the Discord messanger
type=cudatext-plugin
subdir=cuda_discord_status
homepage=https://github.com/TodNaz/cuda_discord_status
```

Repo тоже тогда стОит переименовать, плиз

homepage=https://github.com/TodNaz/cuda_discord_status

**Comment by TodNaz** [comment]
В коммите 56a0a52 были применены такие настройки, репозиторий тоже переименовал.
