### ISSUE TITLE
does user need to change this 'magic number'?

### ISSUE THREAD

**Issue by Alexey-T** [TodNaz/cuda_discord_status#6]
self.rpc = Presence('913493054747447386')

**Comment by TodNaz** [comment]
Никак нет. Данное магическое число - идентификатор приложения, что зарегистрирован в discord'е для отображения статуса. Смена его почти является бессмыслицей, только если пользователь такого плагина не захочет перевести отображения статуса для другого приложения с другими картинками.

**Comment by Alexey-T** [comment]
OK
